### ISSUE TITLE
Flow errors do not update on edit in Windows

### ISSUE THREAD

**Issue by vidongls** [flow/flow-for-vscode#444] opened 2022-08-18 04:18 UTC
First time check:
![image](https://user-images.githubusercontent.com/59497657/185292442-4a35cdb5-3235-47a2-92d2-22ed819182e7.png)
After correcting:
![image](https://user-images.githubusercontent.com/59497657/185292512-47d3d4a5-4651-4c4c-80c2-49006992f241.png)
.babelrc
{
"presets": ["@babel/preset-flow"]
}

.flowconfig
[ignore]
<PROJECT_ROOT>/node_modules/.*
<PROJECT_ROOT>/node_modules/test/resolver/malformed_package_json/.*
<PROJECT_ROOT>/node_modules/*
<PROJECT_ROOT>/build/.*
[include]

[libs]

[lints]

[options]

[strict]

file Log:
[DzCzBLearnJszBtestflow.log](https://github.com/flow/flow-for-vscode/files/9367591/DzCzBLearnJszBtestflow.log)

I'm having trouble using not checking and only checking once. And the server is stopped continuously

**Comment by psychobolt** [comment] 2022-11-06 23:02
Possibly related: https://github.com/facebook/flow/issues/8932

**Comment by mroch** [comment] 2023-03-27 00:58
Duplicate of #443

**Closed by mroch** 2023-03-27 00:58 UTC
