### ISSUE TITLE
react-native

### ISSUE THREAD

**Issue by saumar16** [flow/flow-for-vscode#387] opened 2020-05-18 17:00 UTC
no work 
react-native-cli: 2.0.1
react-native: 0.62.2
flow version 0.125.1

**Comment by orta** [comment] 2020-05-19 02:41
Please provide a more useful error report - what isn't working? what have you tried?

**Comment by 8zero7** [comment] 2020-08-20 12:09
I'm assuming @saumar16 is having the same issue that I am. The boilerplate code when creating a new react-native app using `npx react-native ...` uses a flowversion of ^0.122.0 by default. this version is required for react native. The VSCode extension has version 0.107.0 so you receive an error message: `Failed to start flow Error: Wrong version of Flow. The config specifies version ^0.122.0 but this is version 0.107.0`

Is an update to the latest version of flow anticipated for this extension?

**Comment by beng970804** [comment] 2021-04-07 09:40
No update on this issue?

**Comment by noppa** [comment] 2021-04-07 10:05
Hard to update the issue to anything but perhaps to "closed as can't reproduce" when the issue description is so lacking. _If_ @8zero7 's guess is correct, then yes, there's PR #413 to update the Flow version of this extension. Meanwhile, any Flow-using project should probably include Flow as a dependency, anyway. If `npx react-native` doesn't do this automatically, you can just `npm i -D flow-bin` to add Flow as a devDependency and then this extension should use your installed version automatically, right?

**Closed** 2022-07-31 21:36 UTC
